version: '3'
    
services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports: 
      - "27017:27017"
    volumes: 
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor 

  web:
    build: .
    container_name: graphql
    image: demo:v1
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    environment: 
      DATABASE_HOST: 'db'
    depends_on:
      - db
